repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy (python)
        entry: cargo clippy --all-targets -F python -- -D warnings
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test (python)
        entry: cargo test -F python
        language: system
        pass_filenames: false
      - id: ty
        name: ty
        entry: ty check . --exclude=.yamloom.py --exclude=examples
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        pass_filenames: false
  - repo: https://github.com/denehoffman/yamloom
    rev: yamloom-v0.5.5
    hooks:
      - id: yamloom-sync
        files: ^(\.github/workflows/.*\.ya?ml|\.yamloom\.py)$
