[package]
name = "ganesh"
version = "0.11.2"
edition = "2021"
description = "Function minimization in Rust, simplified"
documentation = "https://docs.rs/ganesh"
readme = "README.md"
homepage = "https://github.com/denehoffman/ganesh"
repository = "https://github.com/denehoffman/ganesh"
license = "MIT OR Apache-2.0"
keywords = ["optimization", "minimization"]
categories = ["science", "mathematics"]


[dependencies]
nalgebra = "0.33.0"
num = "0.4.3"

[dev-dependencies]
criterion = "0.5.1"
float-cmp = "0.10.0"

[[bench]]
name = "rosenbrock_benchmark"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs/docs-header.html"]
