[package]
name = "ganesh"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
nalgebra = "0.33.0"
derive_builder = "0.20.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs-header.html"]
