[package]
name = "ganesh"
version = "0.1.1"
edition = "2021"
description = "Function minimization in Rust, simplified"
documentation = "https://docs.rs/ganesh"
readme = "README.md"
homepage = "https://github.com/denehoffman/ganesh"
repository = "https://github.com/denehoffman/ganesh"
license-file = "LICENSE"
keywords = ["optimization", "minimization"]
categories = ["science", "mathematics"]


[dependencies]
num-traits = "0.2.19"
nalgebra = "0.33.0"
typed-builder = "0.18.2"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs-header.html"]
