[package]
name = "ganesh"
version = "0.20.0"
edition = "2021"
description = "Function minimization in Rust, simplified"
documentation = "https://docs.rs/ganesh"
readme = "README.md"
homepage = "https://github.com/denehoffman/ganesh"
repository = "https://github.com/denehoffman/ganesh"
license = "MIT OR Apache-2.0"
keywords = ["optimization", "minimization"]
categories = ["science", "mathematics"]
rust-version = "1.69.0"
exclude = ["multimodal_ess/*.svg", "multimodal_ess/*.png", "pso/*.gif", "*.pkl"]

[dependencies]
nalgebra = { version = "0.33.0", features = ["serde-serialize"] }
ctrlc = "3.4.5"
lazy_static = "1.5.0"
dyn-clone = "1.0.17"
serde = { version = "1.0.214", features = ["derive", "rc"] }
serde-pickle = "1.2.0"
spec_math = "0.1.6"
fastrand = "2.2.0"
fastrand-contrib = "0.1.0"
logsumexp = "0.1.0"
parking_lot = { version = "0.12.3", features = ["serde"] }
rustfft = "6.2.0"

[dev-dependencies]
criterion = { version = "2.7.2", package = "codspeed-criterion-compat", features = [
  "html_reports",
] }
approx = "0.5.1"

[features]
default = []
f32 = []

[[bench]]
name = "nelder_mead_benchmark"
harness = false

[[bench]]
name = "lbfgsb_benchmark"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs/docs-header.html"]
