from typing import Any, TypeAlias

import numpy as np
import numpy.typing as npt

from ganesh._typing import MCMCDiagnostics, Point, Swarm

__version__: str

BoundsList: TypeAlias = list[tuple[float | None, float | None]]
FloatArray: TypeAlias = npt.NDArray[np.float64]
SummaryDict: TypeAlias = dict[str, Any]

class GaneshError(Exception): ...
class GaneshConfigError(GaneshError): ...
class GaneshNumericalError(GaneshError): ...

class StatusMessage:
    @property
    def status_type(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    def to_dict(self) -> SummaryDict: ...

class MinimizationSummary:
    @property
    def bounds(self) -> BoundsList | None: ...
    @property
    def parameter_names(self) -> list[str] | None: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def x0(self) -> FloatArray: ...
    @property
    def x(self) -> FloatArray: ...
    @property
    def std(self) -> FloatArray: ...
    @property
    def fx(self) -> float: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def n_g_evals(self) -> int: ...
    @property
    def n_h_evals(self) -> int: ...
    @property
    def covariance(self) -> FloatArray: ...
    def to_dict(self) -> SummaryDict: ...

class MCMCSummary:
    @property
    def bounds(self) -> BoundsList | None: ...
    @property
    def parameter_names(self) -> list[str] | None: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def n_g_evals(self) -> int: ...
    @property
    def n_h_evals(self) -> int: ...
    @property
    def dimension(self) -> tuple[int, int, int]: ...
    def chain_storage(self) -> SummaryDict: ...
    def diagnostics(
        self, *, burn: int | None = None, thin: int | None = None
    ) -> MCMCDiagnostics: ...
    def chain(
        self, *, burn: int | None = None, thin: int | None = None, flat: bool = False
    ) -> FloatArray: ...
    def to_dict(self) -> SummaryDict: ...

class MultiStartSummary:
    @property
    def runs(self) -> list[MinimizationSummary]: ...
    @property
    def best_run_index(self) -> int | None: ...
    @property
    def best_run(self) -> MinimizationSummary | None: ...
    @property
    def restart_count(self) -> int: ...
    @property
    def completed_runs(self) -> int: ...
    def to_dict(self) -> SummaryDict: ...

class SimulatedAnnealingSummary:
    @property
    def bounds(self) -> BoundsList | None: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def x0(self) -> FloatArray: ...
    @property
    def x(self) -> FloatArray: ...
    @property
    def fx(self) -> float: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def n_g_evals(self) -> int: ...
    @property
    def n_h_evals(self) -> int: ...
    def to_dict(self) -> SummaryDict: ...

class GradientStatus:
    @property
    def message(self) -> StatusMessage: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def x(self) -> FloatArray: ...
    @property
    def fx(self) -> float: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def n_g_evals(self) -> int: ...
    @property
    def n_h_evals(self) -> int: ...
    @property
    def hess(self) -> FloatArray | None: ...
    @property
    def cov(self) -> FloatArray | None: ...
    @property
    def err(self) -> FloatArray | None: ...
    def to_dict(self) -> SummaryDict: ...

class GradientFreeStatus:
    @property
    def message(self) -> StatusMessage: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def x(self) -> FloatArray: ...
    @property
    def fx(self) -> float: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def hess(self) -> FloatArray | None: ...
    @property
    def cov(self) -> FloatArray | None: ...
    @property
    def err(self) -> FloatArray | None: ...
    def to_dict(self) -> SummaryDict: ...

class EnsembleStatus:
    @property
    def message(self) -> StatusMessage: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def n_g_evals(self) -> int: ...
    @property
    def dimension(self) -> tuple[int, int, int]: ...
    def chain(
        self, *, burn: int | None = None, thin: int | None = None, flat: bool = False
    ) -> FloatArray: ...
    def to_dict(self) -> SummaryDict: ...

class SwarmStatus:
    @property
    def message(self) -> StatusMessage: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def gbest(self) -> Point: ...
    @property
    def initial_gbest(self) -> Point: ...
    @property
    def n_f_evals(self) -> int: ...
    @property
    def swarm(self) -> Swarm: ...
    def to_dict(self) -> SummaryDict: ...

class SimulatedAnnealingStatus:
    @property
    def message(self) -> StatusMessage: ...
    @property
    def status_type(self) -> str: ...
    @property
    def message_text(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def temperature(self) -> float: ...
    @property
    def initial(self) -> Point: ...
    @property
    def best(self) -> Point: ...
    @property
    def current(self) -> Point: ...
    @property
    def n_f_evals(self) -> int: ...
    def to_dict(self) -> SummaryDict: ...

def _testing_sample_minimization_summary() -> MinimizationSummary: ...
def _testing_sample_mcmc_summary() -> MCMCSummary: ...
def _testing_sample_simulated_annealing_summary() -> SimulatedAnnealingSummary: ...
def _testing_sample_multistart_summary() -> MultiStartSummary: ...
def _testing_sample_gradient_status() -> GradientStatus: ...
def _testing_sample_gradient_free_status() -> GradientFreeStatus: ...
def _testing_sample_ensemble_status() -> EnsembleStatus: ...
def _testing_sample_swarm_status() -> SwarmStatus: ...
def _testing_sample_simulated_annealing_status() -> SimulatedAnnealingStatus: ...
