---
name: CodSpeed
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch: ~
jobs:
  benchmarks:
    name: Run Benchmarks
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Rust Tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed
      - run: cargo codspeed build
      - name: CodSpeed Action
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}