---
name: Rust Checks
"on":
  - pull_request
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  rust-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test
      - name: Check all features
        run: cargo check --all-features