---
name: Rust Checks
"on":
  - pull_request
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  rust-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Clippy
        run: cargo clippy
      - name: Clippy (python)
        run: cargo clippy -F python
      - name: Test
        run: cargo test
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
      - run: |-
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install matplotlib corner joblib polars matplotloom pytest
      - run: "uvx --with \"maturin[patchelf]>=1.7,<2\" maturin develop --uv"
      - name: Test (python)
        run: cargo test -F python
  check-readme:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Rust Tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme
      - name: Check README
        run: cargo rdme --check