name: Rust

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -r --verbose
      - name: Run tests
        run: cargo test -r --verbose
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the README.md is up to date.
        run: |
          cargo install cargo-rdme
          cargo rdme --check
